### ISSUE TITLE
Improve error reporting on piece fetch

### ISSUE THREAD

**Issue by erkkah** [allihoopa/AllihoopaCore-ObjC#24]
We have had a number of reports of "A required field was missing in server response" errors.
Since it's been hard to track down, let's add more detailed error reporting in these instances so we can learn what is going on.

**Comment by iKenndac** [comment]
This happens when one of the following keys is either missing or invalid for:

- uuid
- title
- createdAt
- url
- author / username
- coverImage / url
- lengthUs

**Comment by erkkah** [comment]
Exactly. And we have currently no idea how any of them could be missing or invalid.
So the idea is to make that message more detailed, or log the full response or something, to help us find the problem.

**Comment by Boerworz** [comment]
This was adressed in https://github.com/allihoopa/AllihoopaCore-ObjC/pull/25, which was released as part of [AllihoopaCore-ObjC 4.1.0](https://github.com/allihoopa/AllihoopaCore-ObjC/releases/tag/4.1.0).
